package com.teamsmartstreamlabs.smartbackpacks;

import com.mojang.logging.LogUtils;
import com.teamsmartstreamlabs.smartbackpacks.backpack.BackpackCraftingHandler;
import com.teamsmartstreamlabs.smartbackpacks.loot.ModLootEvents;
import com.teamsmartstreamlabs.smartbackpacks.mobbackpack.MobBackpackCommands;
import com.teamsmartstreamlabs.smartbackpacks.mobbackpack.MobBackpackHandler;
import com.teamsmartstreamlabs.smartbackpacks.network.ModPayloads;
import com.teamsmartstreamlabs.smartbackpacks.pickup.PickupNotifierServer;
import com.teamsmartstreamlabs.smartbackpacks.registry.ModBlockEntities;
import com.teamsmartstreamlabs.smartbackpacks.registry.ModBlocks;
import com.teamsmartstreamlabs.smartbackpacks.registry.ModCapabilities;
import com.teamsmartstreamlabs.smartbackpacks.registry.ModCreativeTabs;
import com.teamsmartstreamlabs.smartbackpacks.registry.ModDataComponents;
import com.teamsmartstreamlabs.smartbackpacks.registry.ModItems;
import com.teamsmartstreamlabs.smartbackpacks.registry.ModLootFunctions;
import com.teamsmartstreamlabs.smartbackpacks.worldgen.ModCampStructures;
import com.teamsmartstreamlabs.smartbackpacks.worldgen.CampTreeClearance;
import com.teamsmartstreamlabs.smartbackpacks.registry.ModMenuTypes;
import com.teamsmartstreamlabs.smartbackpacks.registry.ModRecipeSerializers;
import com.teamsmartstreamlabs.smartbackpacks.registry.ModRecipeTypes;
import com.teamsmartstreamlabs.smartbackpacks.upgrade.BlastFurnaceUpgradeHandler;
import com.teamsmartstreamlabs.smartbackpacks.upgrade.AutoSmeltingUpgradeMenuHandler;
import com.teamsmartstreamlabs.smartbackpacks.upgrade.AutoFeedUpgradeHandler;
import com.teamsmartstreamlabs.smartbackpacks.upgrade.BrewingStandUpgradeHandler;
import com.teamsmartstreamlabs.smartbackpacks.upgrade.BuilderUpgradeHandler;
import com.teamsmartstreamlabs.smartbackpacks.upgrade.CapacityWarningUpgradeHandler;
import com.teamsmartstreamlabs.smartbackpacks.upgrade.CourierUpgradeHandler;
import com.teamsmartstreamlabs.smartbackpacks.upgrade.DepositUpgradeHandler;
import com.teamsmartstreamlabs.smartbackpacks.upgrade.CompressionUpgradeHandler;
import com.teamsmartstreamlabs.smartbackpacks.upgrade.FurnaceUpgradeHandler;
import com.teamsmartstreamlabs.smartbackpacks.upgrade.LightUpgradeHandler;
import com.teamsmartstreamlabs.smartbackpacks.upgrade.NightVisionUpgradeHandler;
import com.teamsmartstreamlabs.smartbackpacks.upgrade.FlightUpgradeHandler;
import com.teamsmartstreamlabs.smartbackpacks.upgrade.RepairUpgradeHandler;
import com.teamsmartstreamlabs.smartbackpacks.upgrade.FallProtectionUpgradeHandler;
import com.teamsmartstreamlabs.smartbackpacks.upgrade.MagnetUpgradeHandler;
import com.teamsmartstreamlabs.smartbackpacks.upgrade.PickupUpgradeHandler;
import com.teamsmartstreamlabs.smartbackpacks.upgrade.QuiverUpgradeHandler;
import com.teamsmartstreamlabs.smartbackpacks.upgrade.RescueUpgradeHandler;
import com.teamsmartstreamlabs.smartbackpacks.upgrade.RestockUpgradeHandler;
import com.teamsmartstreamlabs.smartbackpacks.upgrade.SmokerUpgradeHandler;
import com.teamsmartstreamlabs.smartbackpacks.upgrade.SoulboundUpgradeHandler;
import com.teamsmartstreamlabs.smartbackpacks.upgrade.DeathEmergencyKitHandler;
import com.teamsmartstreamlabs.smartbackpacks.upgrade.SurvivalAssistUpgradeHandler;
import com.teamsmartstreamlabs.smartbackpacks.upgrade.TorchPlacerUpgradeHandler;
import com.teamsmartstreamlabs.smartbackpacks.upgrade.VoidboundUpgradeHandler;
import com.teamsmartstreamlabs.smartbackpacks.upgrade.VoidUpgradeHandler;
import org.slf4j.Logger;

import net.neoforged.fml.event.lifecycle.FMLCommonSetupEvent;
import net.neoforged.bus.api.IEventBus;
import net.neoforged.fml.ModContainer;
import net.neoforged.fml.common.Mod;
import net.neoforged.fml.config.ModConfig;
import net.neoforged.neoforge.common.NeoForge;
import net.neoforged.neoforge.event.entity.EntityInvulnerabilityCheckEvent;
import net.neoforged.neoforge.event.entity.EntityJoinLevelEvent;
import net.neoforged.neoforge.event.entity.living.LivingDropsEvent;
import net.neoforged.neoforge.event.entity.living.LivingDeathEvent;
import net.neoforged.neoforge.event.entity.item.ItemExpireEvent;
import net.neoforged.neoforge.event.level.ExplosionEvent;
import net.neoforged.neoforge.event.tick.EntityTickEvent;

@Mod(SmartBackpacks.MOD_ID)
public class SmartBackpacks {
    public static final String MOD_ID = "smartbackpacks";
    public static final Logger LOGGER = LogUtils.getLogger();

    public SmartBackpacks(IEventBus modEventBus, ModContainer modContainer) {
        modContainer.registerConfig(ModConfig.Type.COMMON, SmartBackpacksConfig.SPEC, "smartbackpacksconfig.toml");
        ModBlocks.register(modEventBus);
        ModBlockEntities.register(modEventBus);
        ModDataComponents.register(modEventBus);
        ModRecipeSerializers.register(modEventBus);
        ModRecipeTypes.register(modEventBus);
        ModItems.register(modEventBus);
        ModLootFunctions.register(modEventBus);
        ModCampStructures.register(modEventBus);
        com.teamsmartstreamlabs.smartbackpacks.registry.ModSounds.register(modEventBus);
        ModMenuTypes.register(modEventBus);
        ModCreativeTabs.register(modEventBus);
        ModPayloads.register(modEventBus);
        modEventBus.addListener(ModCapabilities::registerCapabilities);
        NeoForge.EVENT_BUS.addListener(BackpackCraftingHandler::onItemCrafted);
        NeoForge.EVENT_BUS.addListener(ModLootEvents::onLootTableLoad);
        NeoForge.EVENT_BUS.addListener(AutoSmeltingUpgradeMenuHandler::onPlayerTick);
        NeoForge.EVENT_BUS.addListener(BlastFurnaceUpgradeHandler::onPlayerTick);
        NeoForge.EVENT_BUS.addListener(AutoFeedUpgradeHandler::onPlayerTick);
        NeoForge.EVENT_BUS.addListener(BrewingStandUpgradeHandler::onPlayerTick);
        NeoForge.EVENT_BUS.addListener(FurnaceUpgradeHandler::onPlayerTick);
        NeoForge.EVENT_BUS.addListener(CompressionUpgradeHandler::onPlayerTick);
        NeoForge.EVENT_BUS.addListener(SmokerUpgradeHandler::onPlayerTick);
        NeoForge.EVENT_BUS.addListener(SurvivalAssistUpgradeHandler::onPlayerTick);
        NeoForge.EVENT_BUS.addListener(LightUpgradeHandler::onPlayerTick);
        NeoForge.EVENT_BUS.addListener(NightVisionUpgradeHandler::onPlayerTick);
        NeoForge.EVENT_BUS.addListener(FlightUpgradeHandler::onPlayerTick);
        NeoForge.EVENT_BUS.addListener(RepairUpgradeHandler::onPlayerTick);
        NeoForge.EVENT_BUS.addListener(FallProtectionUpgradeHandler::onPlayerTick);
        NeoForge.EVENT_BUS.addListener(LightUpgradeHandler::onPlayerLoggedOut);
        NeoForge.EVENT_BUS.addListener(NightVisionUpgradeHandler::onPlayerLoggedOut);
        NeoForge.EVENT_BUS.addListener(FlightUpgradeHandler::onPlayerLoggedOut);
        NeoForge.EVENT_BUS.addListener(RepairUpgradeHandler::onPlayerLoggedOut);
        NeoForge.EVENT_BUS.addListener(FallProtectionUpgradeHandler::onPlayerLoggedOut);
        NeoForge.EVENT_BUS.addListener(MagnetUpgradeHandler::onPlayerTick);
        NeoForge.EVENT_BUS.addListener(MagnetUpgradeHandler::onItemPickup);
        NeoForge.EVENT_BUS.addListener(PickupUpgradeHandler::onPlayerTick);
        NeoForge.EVENT_BUS.addListener(PickupUpgradeHandler::onItemPickup);
        NeoForge.EVENT_BUS.addListener(QuiverUpgradeHandler::onLivingGetProjectile);
        NeoForge.EVENT_BUS.addListener(QuiverUpgradeHandler::onPlayerTick);
        NeoForge.EVENT_BUS.addListener(RescueUpgradeHandler::onPlayerTick);
        NeoForge.EVENT_BUS.addListener(RescueUpgradeHandler::onLivingDamagePre);
        NeoForge.EVENT_BUS.addListener(RescueUpgradeHandler::onLivingDeath);
        NeoForge.EVENT_BUS.addListener(BuilderUpgradeHandler::onRightClickBlock);
        NeoForge.EVENT_BUS.addListener(BuilderUpgradeHandler::onBlockPlaced);
        NeoForge.EVENT_BUS.addListener(BuilderUpgradeHandler::onPlayerTick);
        NeoForge.EVENT_BUS.addListener(BuilderUpgradeHandler::onPlayerLoggedOut);
        NeoForge.EVENT_BUS.addListener(TorchPlacerUpgradeHandler::onPlayerTick);
        NeoForge.EVENT_BUS.addListener(TorchPlacerUpgradeHandler::onPlayerLoggedOut);
        NeoForge.EVENT_BUS.addListener(CapacityWarningUpgradeHandler::onPlayerTick);
        NeoForge.EVENT_BUS.addListener(CourierUpgradeHandler::onPlayerTick);
        NeoForge.EVENT_BUS.addListener(CourierUpgradeHandler::onRightClickBlock);
        NeoForge.EVENT_BUS.addListener(CapacityWarningUpgradeHandler::onPlayerLoggedOut);
        NeoForge.EVENT_BUS.addListener(RestockUpgradeHandler::onRightClickBlock);
        NeoForge.EVENT_BUS.addListener(DepositUpgradeHandler::onRightClickBlock);
        NeoForge.EVENT_BUS.addListener(VoidUpgradeHandler::onPlayerTick);
        NeoForge.EVENT_BUS.addListener(VoidboundUpgradeHandler::onEntityJoinLevel);
        NeoForge.EVENT_BUS.addListener(VoidboundUpgradeHandler::onItemExpire);
        NeoForge.EVENT_BUS.addListener(VoidboundUpgradeHandler::onEntityTickPre);
        NeoForge.EVENT_BUS.addListener(VoidboundUpgradeHandler::onEntityInvulnerabilityCheck);
        NeoForge.EVENT_BUS.addListener(VoidboundUpgradeHandler::onExplosionDetonate);
        NeoForge.EVENT_BUS.addListener(SoulboundUpgradeHandler::onLivingDrops);
        NeoForge.EVENT_BUS.addListener(SoulboundUpgradeHandler::onPlayerRespawn);
        NeoForge.EVENT_BUS.addListener(DeathEmergencyKitHandler::onLivingDrops);
        NeoForge.EVENT_BUS.addListener(DeathEmergencyKitHandler::onPlayerRespawn);
        NeoForge.EVENT_BUS.addListener(DeathEmergencyKitHandler::onPlayerTick);
        NeoForge.EVENT_BUS.addListener(PickupNotifierServer::onPlayerTick);
        NeoForge.EVENT_BUS.addListener(com.teamsmartstreamlabs.smartbackpacks.progress.BackpackProgression::onPlayerTick);
        NeoForge.EVENT_BUS.addListener(MobBackpackHandler::onSpawnPositionCheck);
        NeoForge.EVENT_BUS.addListener(MobBackpackHandler::onStartTracking);
        NeoForge.EVENT_BUS.addListener(MobBackpackHandler::onLivingDrops);
        NeoForge.EVENT_BUS.addListener(MobBackpackCommands::onRegisterCommands);
        NeoForge.EVENT_BUS.addListener(CampTreeClearance::onChunkLoad);
        NeoForge.EVENT_BUS.addListener(CampTreeClearance::onServerTick);
    }
}
